CREATE DATABASE damasroyale;

CREATE USER 'DamasRoyale'@'localhost' IDENTIFIED BY 'NoSeJugarAlAjedrez';

GRANT SELECT, INSERT, UPDATE, DELETE ON damasroyale.* TO 'DamasRoyale'@'localhost';

USE damasroyale;

CREATE TABLE USUARIOS (
    ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(32) NOT NULL,
    EMAIL VARCHAR(64) NOT NULL,
    CONTRASENYA VARCHAR(64) NOT NULL,
    IMAGEN VARCHAR(64) NOT NULL,
    REGISTRO DATETIME NOT NULL,
    ESTADO BOOLEAN NOT NULL
);

CREATE TABLE ACTIVACIONES (
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IDUSUARIO INT(11) NOT NULL,
    CODIGO VARCHAR(15) NOT NULL,
    FOREIGN KEY (IDUSUARIO)
        REFERENCES USUARIOS (ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PARTIDAS (
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IDUSUARIO_A INT(11) NOT NULL,
    IDUSUARIO_B INT(11),
    FINALIZADA BOOLEAN,
    FOREIGN KEY (IDUSUARIO_A)
        REFERENCES USUARIOS (ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (IDUSUARIO_B)
        REFERENCES USUARIOS (ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE RESULTADOS (
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IDPARTIDA INT(11) NOT NULL,
    FECHA_HORA DATETIME NOT NULL,
    TABLAS BOOLEAN,
    GANADOR INT(11),
    PERDEDOR INT(11),
    FOREIGN KEY (IDPARTIDA)
        REFERENCES PARTIDAS (ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (GANADOR)
        REFERENCES USUARIOS (ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (PERDEDOR)
        REFERENCES USUARIOS (ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MOVIMIENTOS (
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IDPARTIDA INT(11) NOT NULL,
    IDUSUARIO INT(11) NOT NULL,
    POS_INICIAL INT(4) NOT NULL,
    POS_FINAL INT(4) NOT NULL,
    FOREIGN KEY (IDPARTIDA)
        REFERENCES PARTIDAS (ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (IDUSUARIO)
        REFERENCES USUARIOS (ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MENSAJES (
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IDPARTIDA INT(11) NOT NULL,
    IDUSUARIO INT(11) NOT NULL,
    HORA TIME NOT NULL,
    TEXTO VARCHAR(255) NOT NULL,
    FOREIGN KEY (IDPARTIDA)
        REFERENCES PARTIDAS (ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (IDUSUARIO)
        REFERENCES USUARIOS (ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);